name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number in the format `v1.2.3`"
        required: true
        type: string
      upload_to_github:
        description: "Upload to GitHub releases"
        default: true
        type: boolean
      deploy_to_itch:
        description: "Deploy to itch.io (if configured)"
        default: true
        type: boolean
      deploy_to_github_pages:
        description: "Deploy web build to GitHub Pages"
        default: false
        type: boolean
      deny_warnings:
        description: "Deny warnings"
        default: false
        type: boolean
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  cargo_build_binary_name: bevy_game
  assets_path: assets
  itch_page: rockcen/chaos-dream
  app_id: rockcen.chaos-dream
  app_package_name: bevy-new-2d
  git_lfs: false
  continuous_deployment_to_itch: true
  continuous_deployment_to_github_pages: false

jobs:
  forward-env:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: "true"
    outputs:
      itch_page: ${{ env.itch_page }}
      continuous_deployment_to_itch: ${{ env.continuous_deployment_to_itch }}
      continuous_deployment_to_github_pages: ${{ env.continuous_deployment_to_github_pages }}

  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Determine version number
        id: version
        run: |
          if [ -n '${{ inputs.version }}' ]; then
            echo "version=${{ inputs.version }}" >> "${GITHUB_OUTPUT}"
          else
            echo "version=$(cargo pkgid | sed 's/.*#//')" >> "${GITHUB_OUTPUT}"
          fi

  build:
    needs:
      - forward-env
      - get-version
    env:
      version: ${{ needs.get-version.outputs.version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up environment
        run: |
          echo "app_package_name=${app_package_name:=${{ env.cargo_build_binary_name }}}" >> "${GITHUB_ENV}"
          echo "app=tmp/app/${app_package_name}" >> "${GITHUB_ENV}"
          echo "package=${app_package_name}-web.zip" >> "${GITHUB_ENV}"

          RUSTFLAGS='-Zthreads=0 -Zshare-generics=y'
          if [ '${{ inputs.deny_warnings }}' = 'true' ]; then
            RUSTFLAGS="${RUSTFLAGS} -Dwarnings"
          fi
          echo "RUSTFLAGS=${RUSTFLAGS}" >> "${GITHUB_ENV}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: ${{ env.git_lfs }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: Restore Rust cache
        if: ${{ github.event_name == 'push' }}
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: release
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Prepare output directories
        run: rm -rf tmp; mkdir -p tmp/binary '${{ env.app }}'

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Bevy CLI
        run: cargo binstall --version 0.1.0-alpha.2 --locked --no-confirm --force --git='https://github.com/TheBevyFlock/bevy_cli' bevy_cli

      - name: Build web bundle
        run: |
          cargo binstall --locked --no-confirm --force wasm-bindgen-cli
          cargo binstall --locked --no-confirm --force wasm-opt
          bevy build --locked --release --yes web --bundle
          mv 'target/bevy_web/web-release/${{ env.cargo_build_binary_name }}' '${{ env.app }}'

      - name: Package app
        working-directory: tmp/app
        run: zip --recurse-paths '${{ env.package }}' '${{ env.app_package_name }}'

      - name: Upload package to workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          path: tmp/app/${{ env.package }}
          name: package-web
          retention-days: 1

      - name: Upload web bundle to workflow artifacts for GitHub Pages
        if: ${{ inputs.deploy_to_github_pages == true || (github.event_name == 'push' && needs.forward-env.outputs.continuous_deployment_to_github_pages == 'true') }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.app }}/${{ env.cargo_build_binary_name }}

      - name: Upload package to GitHub release
        if: ${{ inputs.upload_to_github }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/app/${{ env.package }}
          asset_name: ${{ env.package }}
          release_name: ${{ env.version }}
          tag: ${{ env.version }}
          overwrite: true

  deploy-to-itch:
    runs-on: ubuntu-latest
    needs:
      - forward-env
      - build
    if: ${{ (inputs.deploy_to_itch || (github.event_name == 'push' && needs.forward-env.outputs.continuous_deployment_to_itch == 'true')) && needs.forward-env.outputs.itch_page != '' }}
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          pattern: package-*
          path: tmp

      - name: Install butler
        run: |
          curl -L -o butler.zip 'https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default'
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Upload packages to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          for package in $(ls tmp); do
            ./butler push \
              --fix-permissions \
              --userversion='${{ needs.get-version.outputs.version }}' \
              tmp/"${package}"/* \
              '${{ env.itch_page }}':"${package#package-}"
          done

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    if: ${{ inputs.deploy_to_github_pages || (github.event_name == 'push' && needs.forward-env.outputs.continuous_deployment_to_github_pages == 'true') }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
